version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    entrypoint: sh /app/docker/startup.sh
volumes:
  mysql:
    driver: local